sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t daviddaming/react-test -f ./client/Dockerfile.dev ./client

script:
  # run the test
  - docker run -e CI=true daviddaming/react-test npm test

after_success:
  - docker build -t daviddaming/multi-client ./client
  - docker build -t daviddaming/multi-nginx ./nginx
  - docker build -t daviddaming/multi-server ./server
  - docker build -t daviddaming/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push daviddaming/multi-client
  - docker push daviddaming/multi-nginx
  - docker push daviddaming/multi-server
  - docker push daviddaming/multi-worker
